version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-telegram-bot
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 77.88.8.8
    network_mode: bridge
    environment:
      - TZ=Europe/Moscow
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./logs:/app/logs
    extra_hosts:
      - "api.telegram.org:149.154.167.220"
      - "telegram.org:149.154.167.99"